modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/EnvyWare/BetterDexRewards/issues"

[[mods]]
modId="betterdexrewards"
version="3.5.0"
displayName="BetterDexRewards Forge"
displayURL="https://github.com/EnvyWare"
credits="https://github.com/EnvyWare"
authors="https://github.com/EnvyWare"
updateJSONURL="https://ogn.pixelmonmod.com/update/sm-dr/update.json"
description='''
Adds Dex Rewards
'''

[[dependencies.betterdexrewards]]
modId="forge"
mandatory=true
versionRange="[48.0.22,)"
ordering="NONE"
side="BOTH"

[[dependencies.betterdexrewards]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"